sudo: required
  
services:
  - docker

language: scala

scala:
  - 2.12.5

before_install:
  - docker run --rm -d -p "8080:8080" --name wiremock rodolpheche/wiremock

script:
  - ./sbt clean test

after_success:
  - docker rm -f wiremock

cache:
  directories:
  - "$HOME/.ivy2"
  - "$HOME/.sbt"

branches:
  only:
    - master
