sudo: required

language: scala

jdk: openjdk8
scala:
  - 2.12.5

script:
  - ./sbt clean test

cache:
  directories:
  - "$HOME/.ivy2"
  - "$HOME/.sbt"

branches:
  only:
    - master
notifications:
  slack: sdkman:QdA1XVUuYDjlYL4Z7gm16OEc
